server:
  port: \

spring:
  profiles:
    active: \
  application:
    name: quiron-concursos
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  h2:
    console:
      enabled: true

app:
  url:
    frontend: \
  security:
    token-jwt:
      access-token:
        secret-key: \
        expiration-time: \
      refresh-token:
        secret-key: \
        expiration-time: \
